name: Sync to Hugging Face hub
on:
  push:
    branches: [main, master] # main이나 master 어디에 올려도 작동하도록 추가
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 👈 v4로 업데이트 완료 (경고 해결)
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 👇 아래 줄의 [본인아이디]와 [스페이스이름]을 꼭 수정해주세요! (괄호는 지우세요)
          git remote add space https://developerDH:${HF_TOKEN}@huggingface.co/spaces/developerDH/fashion_rec_sys
          
          # 👇 브랜치 이름 충돌을 방지하는 마법의 명령어 (수정 완료)
          git push --force space HEAD:main
